export default {
    database: process.env.DB_DATABASE,
    user: process.env.DB_USER,
    pass: process.env.DB_PASS,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    // accessKey: 'F8BBA842ECF85',
    // secretKey: 'K951B6PE1waDMi640xX08PD3vg6EkVlz',
    // orderInfo: 'pay with MoMo',
    // partnerCode: 'MOMO',
    // redirectUrl: 'http://localhost:8080/views/home.html',
    // ipnUrl: 'https://b679-115-73-128-174.ngrok-free.app/callback', 
    requestType: 'payWithMethod',
    extraData: '',
    orderGroupId: '',
    autoCapture: true,
    lang: 'vi',
}
